version: '3.4'
services:
  webapp:
    build:
      context: ./
    command: /code/docker-support/dev-init.sh
    ports:
      - "8080:8080"
    tmpfs:
      - /static
    volumes:
      - type: bind
        source: ./
        target: /code
      - type: bind
        source: ./docker-support/dev_settings.py
        target: /acmeproxy_settings.py
        read_only: true
      - ./docker-support/logs/webapp:/logs/
      - type: tmpfs
        target: /tmp
    restart: always

