# Generated by Django 2.2.13 on 2020-06-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0008_auto_20161010_1645"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="authorisation", unique_together=set(),),
        migrations.RemoveField(model_name="authorisation", name="suffix_match",),
    ]
