# Generated by Django 2.2.19 on 2022-08-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0009_auto_20200611_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_ip', models.GenericIPAddressField(verbose_name='Created by IP address')),
                ('permit_domains', models.TextField(help_text='Comma separated list of domains account is allowed to obtain authorisations for.            For example: example.com, .example.com, www.example.org', verbose_name='Permitted domains')),
            ],
        ),
        migrations.RemoveField(
            model_name='authorisation',
            name='account',
        ),
    ]
