# Generated by Django 2.2.19 on 2022-08-10 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0010_auto_20220811_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorisation',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proxy.Account'),
        ),
    ]
