# Generated by Django 2.2.19 on 2022-09-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0011_authorisation_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.CharField(blank=True, help_text='Any applicable notes for the account, such as WR.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='permit_domains',
            field=models.TextField(help_text='Comma separated list of domains the account is allowed to obtain authorisations for.            For example: example.com, .example.com, www.example.org', verbose_name='Permitted domains'),
        ),
    ]
