# Generated by Django 2.2.19 on 2022-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0012_auto_20220915_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='secret',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
