# Generated by Django 2.2.19 on 2022-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0013_auto_20220927_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='secret',
            field=models.CharField(default='8ce317e6d5b2def7a026fcb32e62db15', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='secret',
            field=models.CharField(default='d3f8eeee219fd72c431ed67d5cb31148', max_length=128, unique=True),
        ),
    ]
