# Generated by Django 2.2.19 on 2022-09-29 21:04

from django.db import migrations, models
import proxy.utils


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0014_auto_20220929_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='secret',
            field=models.CharField(default=proxy.utils.generate_secret, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='secret',
            field=models.CharField(default=proxy.utils.generate_secret, max_length=128, unique=True),
        ),
    ]
