name: Lint & Test

on:
  - push
  - pull_request

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev
    - name: Test with pytest
      env:
        DJANGO_SETTINGS_MODULE: acmeproxy_settings
      run: |
        cp docker-support/dev_settings.py acmeproxy_settings.py
        pipenv run pytest -v
  lint:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install linters
      run: |
        pip3 install setuptools
        pip3 install flake8 black isort
    - name: Lint with flake8
      run: |
        python3 -m flake8 .
    - name: Lint with isort
      run: |
        python3 -m isort --check-only -rc .
    - name: Lint with black
      run: |
        python3 -m black --check --diff .
